[package]
name = "arisu-ffxiv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive"] }
ffxiv-chronowatcher = "0.0.4"
tauri = "2.1.1"
tauri-build = "2.0.3"
